name: Release repo as extension ZIP
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create Changelog
        uses: Bullrich/generate-release-changelog@master
        id: changelog
        env:
          REPO: ${{ github.repository }}
      - name: Archive Extension Release
        uses: thedoctor0/zip-release@main
        with:
          type: "zip"
          filename: "random-history-flashback.${{ github.ref }}.zip"
          path: "."
          exclusions: "*.git* *.sh"
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref }}
          body: |
            ${{ steps.changelog.outputs.changelog }}
          artifacts: "random-history-flashback.${{ github.ref }}.zip"
