name: Release repo as extension ZIP
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create Changelog
        uses: Bullrich/generate-release-changelog@master
        id: changelog
        env:
          REPO: ${{ github.repository }}
      - name: Get version code
        id: getversion
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: false
      - name: Archive Extension Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: "zip"
          filename: "random-history-flashback.${{steps.getversion.outputs.tag}}.zip"
          exclusions: "*.git* *.sh"
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{steps.getversion.outputs.tag}}
          body: |
            ${{ steps.changelog.outputs.changelog }}
          artifacts: "random-history-flashback.${{steps.getversion.outputs.tag}}.zip"
